package com.latenighthack.ktbuf.conformance

// GENERATED by tools/generate_conformance_goldens.py -- do not edit by hand.
//
// Produced by serializing conformance.proto fixtures with the reference protobuf
// runtime (protoc --python_out + the google.protobuf library), NOT with ktbuf.
// These constants are therefore a statement about what a real protobuf peer
// sends and accepts.
//
// Regenerate with: python3 tools/generate_conformance_goldens.py
object ConformanceGoldens {
    // AllTypes with every field at its proto3 default -> zero bytes
    const val Empty = ""
    // f_int32 = 42
    const val Int32Only = "082a"
    // f_int32 = -1 (sign-extended to 10 bytes)
    const val Int32Negative = "08ffffffffffffffffff01"
    // f_int32 = Int.MIN_VALUE
    const val Int32Min = "0880808080f8ffffffff01"
    // f_int32 = Int.MAX_VALUE
    const val Int32Max = "08ffffffff07"
    // f_int64 = Long.MIN_VALUE
    const val Int64Min = "1080808080808080808001"
    // f_int64 = Long.MAX_VALUE
    const val Int64Max = "10ffffffffffffffff7f"
    // f_uint32 = UInt.MAX_VALUE
    const val Uint32Max = "18ffffffff0f"
    // f_uint64 = ULong.MAX_VALUE
    const val Uint64Max = "20ffffffffffffffffff01"
    // f_sint32 = -1 (zigzag -> 1)
    const val Sint32Negative = "2801"
    // f_sint32 = Int.MIN_VALUE
    const val Sint32Min = "28ffffffff0f"
    // f_sint64 = -1
    const val Sint64Negative = "3001"
    // f_sint64 = Long.MIN_VALUE
    const val Sint64Min = "30ffffffffffffffffff01"
    // f_fixed32 = UInt.MAX_VALUE
    const val Fixed32Max = "3dffffffff"
    // f_fixed64 = ULong.MAX_VALUE
    const val Fixed64Max = "41ffffffffffffffff"
    // f_sfixed32 = -1
    const val Sfixed32Negative = "4dffffffff"
    // f_sfixed64 = -1
    const val Sfixed64Negative = "51ffffffffffffffff"
    // f_float = 1.0
    const val FloatOne = "5d0000803f"
    // f_float = -2.5
    const val FloatNegative = "5d000020c0"
    // f_float = NaN
    const val FloatNan = "5d0000c07f"
    // f_float = +Infinity
    const val FloatPosInf = "5d0000807f"
    // f_float = -Infinity
    const val FloatNegInf = "5d000080ff"
    // f_double = 1.0
    const val DoubleOne = "61000000000000f03f"
    // f_double = -2.5
    const val DoubleNegative = "6100000000000004c0"
    // f_double = NaN
    const val DoubleNan = "61000000000000f87f"
    // f_double = +Infinity
    const val DoublePosInf = "61000000000000f07f"
    // f_bool = true
    const val BoolTrue = "6801"
    // f_string = 'hello'
    const val StringAscii = "720568656c6c6f"
    // f_string = CJK
    const val StringCjk = "720ce4bda0e5a5bde4b896e7958c"
    // f_string = emoji (surrogate pair)
    const val StringEmoji = "7204f09f8e89"
    // f_bytes = 00 01 FF
    const val BytesSimple = "7a030001ff"
    // f_enum = A (declared value 3)
    const val EnumA = "800103"
    // f_enum = C (declared value 5)
    const val EnumC = "800105"
    // f_inner = { str='in', an_int=7 }
    const val InnerSimple = "8a01060a02696e1007"
    // f_inner with a populated inner_inner
    const val InnerNested = "8a010c0a016110011a052a01623002"
    // f_inner present but empty -> zero-length submessage
    const val InnerEmpty = "8a0100"
    // r_int32 = [1,2,3] (packed)
    const val RepeatedInt32 = "920103010203"
    // r_int32 = [-1,0,1] (packed)
    const val RepeatedInt32Negative = "92010cffffffffffffffffff010001"
    // r_string = ['a','bb',''] (unpacked)
    const val RepeatedString = "9a0101619a010262629a0100"
    // r_inner = two submessages
    const val RepeatedInner = "a201021001a201021002"
    // f_high_field (field 2048) = 9
    const val HighField = "80800109"
    // every field populated, in field-number order
    const val AllPopulated = "08ffffffffffffffffff0110feffffffffffffffff01180320042809300b3d070000004108000000000000004df7ffffff51f6ffffffffffffff5d0000c03f6100000000000004c068017203616c6c7a0201028001048a010d0a0169100b1a062a026969300c9201020d0e9a0101789a010179a20102100f80800110"
    // f_inner whose body exceeds 127 bytes (2-byte length prefix)
    const val LargeInner = "8a01cb010ac8017a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a"
    // OneOfHolder with lead set and no oneof case
    const val OneOfNone = "0801"
    // oneof choice = c_int
    const val OneOfInt = "08011002"
    // oneof choice = c_string
    const val OneOfString = "08011a0173"
    // oneof choice = c_inner
    const val OneOfInner = "080122021003"
    // oneof set to 0 -- explicit presence means it IS written
    const val OneOfIntZero = "1000"
    // the Empty message -> zero bytes
    const val EmptyMessage = ""
    // oneof int + lead, in the order protoc-gen-kt emits
    const val OneOfIntKtbufOrder = "10020801"
    // oneof string + lead, in the order protoc-gen-kt emits
    const val OneOfStringKtbufOrder = "1a01730801"
    // oneof inner + lead, in the order protoc-gen-kt emits
    const val OneOfInnerKtbufOrder = "220210030801"
}
